[package]
name = "blocksense_contracts"
type = "contract"
authors = ["Nikolay Kostadinov <nikolaykostadinov21@gmail.com>"]
compiler_version = ">=0.35.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "aztec-packages-v0.66.0", directory = "noir-projects/aztec-nr/aztec" }
